---
abstract: 'Mock digest interface to return size of message'
author:
  - 'Jason M Mills, C<< <jmmills at cpan.org> >>'
  - 'Jason M Mills <jmmills@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Digest-Mock-Size
no_index:
  directory:
    - inc
    - t
requires:
  Digest::base: 0
  namespace::clean: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_1
